### ISSUE TITLE
Project infrastructure

### ISSUE THREAD

**Issue by politan** [politan/quizverse#2]
## Feature Description
This feature contains all of basic project work - starts from project creation, tools & framework configuration, finish at deploying code to Github with basic CI workflow.

## Tasks

- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9

## Acceptance Criteria
- [x] Basic project structure is created
- [x] Vue project is configured and up to run
- [x] All tools all configured (ESLint & Prettier)
- [x] Basic test can run without problem
- [x] Github Actions basic configuration with build

## Technical Requirements
- [x] Vue 3 (Composition API)
- [x] Typescript
- [x] Github Actions
- [x] Vite
- [x] Tailwind CSS

## Dependencies
[ None ]

## Additional Notes
[ None ]
